### ISSUE TITLE
Fix Cython dependencies

### ISSUE THREAD

**Issue by strahlex** [machinekit/machinekit#781]
And it hit me https://github.com/machinekit/machinekit/blob/master/src/hal/cython/Submakefile#L23

On Debian stretch I get:

````
Compiling hal/cython/machinekit/hal.c
hal/cython/machinekit/hal.c:1177:59: error: unknown type name ‘comp_type’
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_comp_type(comp_type value);
                                                           ^
hal/cython/machinekit/hal.c:1179:60: error: unknown type name ‘comp_state’
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_comp_state(comp_state value);
                                                            ^
hal/cython/machinekit/hal.c:1189:62: error: unknown type name ‘report_phase’
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_report_phase(report_phase value);
                                                              ^
hal/cython/machinekit/hal.c: In function ‘inithal’:
hal/cython/machinekit/hal.c:40092:15: warning: implicit declaration of function ‘__Pyx_PyInt_From_comp_type’ [-Wimplicit-function-declaration]
   __pyx_t_2 = __Pyx_PyInt_From_comp_type(TYPE_INVALID); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; __pyx_clineno = __LINE__; goto __pyx_L1
               ^
hal/cython/machinekit/hal.c:40092:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   __pyx_t_2 = __Pyx_PyInt_From_comp_type(TYPE_INVALID); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 28; __pyx_clineno = __LINE__; goto __pyx_L1
             ^
hal/cython/machinekit/hal.c:40104:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   __pyx_t_2 = __Pyx_PyInt_From_comp_type(TYPE_RT); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 29; __pyx_clineno = __LINE__; goto __pyx_L1_erro
             ^
hal/cython/machinekit/hal.c:40116:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   __pyx_t_2 = __Pyx_PyInt_From_comp_type(TYPE_USER); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 30; __pyx_clineno = __LINE__; goto __pyx_L1_er
             ^
hal/cython/machinekit/hal.c:40128:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   __pyx_t_2 = __Pyx_PyInt_From_comp_type(TYPE_REMOTE); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 31; __pyx_clineno = __LINE__; goto __pyx_L1_
             ^
hal/cython/machinekit/hal.c:40140:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   __pyx_t_2 = __Pyx_PyInt_From_comp_type(TYPE_HALLIB); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 32; __pyx_clineno = __LINE__; goto __pyx_L1_
             ^
hal/cython/machinekit/hal.c:40152:15: warning: implicit declaration of function ‘__Pyx_PyInt_From_comp_state’ [-Wimplicit-function-declaration]
   __pyx_t_2 = __Pyx_PyInt_From_comp_state(COMP_INVALID); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; __pyx_clineno = __LINE__; goto __pyx_L
               ^
hal/cython/machinekit/hal.c:40152:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   __pyx_t_2 = __Pyx_PyInt_From_comp_state(COMP_INVALID); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 34; __pyx_clineno = __LINE__; goto __pyx_L
             ^
hal/cython/machinekit/hal.c:40164:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   __pyx_t_2 = __Pyx_PyInt_From_comp_state(COMP_INITIALIZING); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 35; __pyx_clineno = __LINE__; goto __
             ^
hal/cython/machinekit/hal.c:40176:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   __pyx_t_2 = __Pyx_PyInt_From_comp_state(COMP_UNBOUND); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 36; __pyx_clineno = __LINE__; goto __pyx_L
             ^
hal/cython/machinekit/hal.c:40188:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   __pyx_t_2 = __Pyx_PyInt_From_comp_state(COMP_BOUND); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 37; __pyx_clineno = __LINE__; goto __pyx_L1_
             ^
hal/cython/machinekit/hal.c:40200:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   __pyx_t_2 = __Pyx_PyInt_From_comp_state(COMP_READY); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 38; __pyx_clineno = __LINE__; goto __pyx_L1_
             ^
hal/cython/machinekit/hal.c:40356:15: warning: implicit declaration of function ‘__Pyx_PyInt_From_report_phase’ [-Wimplicit-function-declaration]
   __pyx_t_2 = __Pyx_PyInt_From_report_phase(REPORT_BEGIN); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx
               ^
hal/cython/machinekit/hal.c:40356:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   __pyx_t_2 = __Pyx_PyInt_From_report_phase(REPORT_BEGIN); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 56; __pyx_clineno = __LINE__; goto __pyx
             ^
hal/cython/machinekit/hal.c:40368:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   __pyx_t_2 = __Pyx_PyInt_From_report_phase(REPORT_SIGNAL); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 57; __pyx_clineno = __LINE__; goto __py
             ^
hal/cython/machinekit/hal.c:40380:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   __pyx_t_2 = __Pyx_PyInt_From_report_phase(REPORT_PIN); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 58; __pyx_clineno = __LINE__; goto __pyx_L
             ^
hal/cython/machinekit/hal.c:40392:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   __pyx_t_2 = __Pyx_PyInt_From_report_phase(REPORT_END); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 59; __pyx_clineno = __LINE__; goto __pyx_L
             ^
hal/cython/machinekit/hal.c:40404:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   __pyx_t_2 = __Pyx_PyInt_From_comp_type(TYPE_INVALID); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 61; __pyx_clineno = __LINE__; goto __pyx_L1
             ^
hal/cython/machinekit/hal.c:40416:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   __pyx_t_2 = __Pyx_PyInt_From_comp_type(TYPE_RT); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 62; __pyx_clineno = __LINE__; goto __pyx_L1_erro
             ^
hal/cython/machinekit/hal.c:40428:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   __pyx_t_2 = __Pyx_PyInt_From_comp_type(TYPE_USER); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 63; __pyx_clineno = __LINE__; goto __pyx_L1_er
             ^
hal/cython/machinekit/hal.c:40440:13: warning: assignment makes pointer from integer without a cast [-Wint-conversion]
   __pyx_t_2 = __Pyx_PyInt_From_comp_type(TYPE_REMOTE); if (unlikely(!__pyx_t_2)) {__pyx_filename = __pyx_f[0]; __pyx_lineno = 64; __pyx_clineno = __LINE__; goto __pyx_L1_
             ^
hal/cython/machinekit/hal.c: At top level:
hal/cython/machinekit/hal.c:43433:59: error: unknown type name ‘comp_type’
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_comp_type(comp_type value) {
                                                           ^
hal/cython/machinekit/hal.c:43459:60: error: unknown type name ‘comp_state’
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_comp_state(comp_state value) {
                                                            ^
hal/cython/machinekit/hal.c:43589:62: error: unknown type name ‘report_phase’
 static CYTHON_INLINE PyObject* __Pyx_PyInt_From_report_phase(report_phase value) {
                                                              ^
Makefile:379: recipe for target 'objects/hal/cython/machinekit/hal.o' failed
make: *** [objects/hal/cython/machinekit/hal.o] Error 1
make: Leaving directory '/home/alexander/bin/machinekit-1/src'
````

Any ideas how to resolve the issue? The cython version is the same as in jessie-backports and it works fine with that.

**Comment by ArcEye** [comment]
https://groups.google.com/forum/#!topic/machinekit/HCpxjxZukf8

This relates to the same errors, with a mix of stretch and jessie packages

Again, the cython version was 0.21.1 (ie the same as Jessie)

The 'unknown types' are defined in src/hal/lib/hal.h and hal_group.h and those files are
included in src/hal/cython/machinekit/hal.c

On a normal C compile I would start looking at the $INCLUDEPATH, but I know diddly about cython

**Comment by strahlex** [comment]
Looks like Cython is not working with gcc5 and Protobuf on stretch is compiled against gcc5 and not working with gcc-4.9. Kind of a locked in situation. Probably have to use a VM for now.

**Comment by mhaberler** [comment]
see issue #740 

gcc5 managed to break the ABI wholesale and repair on a per-package level is in progress

avoid gcc5 for now - wast of time

**Comment by strahlex** [comment]
@mhaberler gcc5 is only part of the deal

I tracked this issue down to Cython 0.23 from either stretch or the jessie-backports. The same error happens when using the package from jessie-backports on a pure jessie installation with gcc-4.9.

I cannot avoid gcc5 at the moment since all libraries on stretch are built against it. (I have to use stretch because of the Broadwell CPU) I hope that the rest of the dependencies work out.

**Comment by bobvanderlinden** [comment]
The errors were fixed for me with:
https://github.com/bobvanderlinden/machinekit/commit/75bac131ede7458b07aab95e7bc377da0960ee55

Compiling it with clang resulted in more intuitive output suggesting to use `enum comp_type` instead of `comp_type`.

I wasn't sure this was also happening on master, but if it is a problem there too, it might be a good idea to do a PR?

**Comment by ArcEye** [comment]
I don't pretend to understand cython, but comp_type is already an enum defined in hal.h

Are you saying you built MK to a running completion just changing this?

I got around the cython issue on stretch by using gcc-4.9 and the jessie packages, but then hit more problems with building the machinetalk section of the code.

**Comment by bobvanderlinden** [comment]
@ArcEye The problem is that `comp_type` is not a typedefed enum (so you need to refer to it as `enum comp_type`), however in `hal_const.pxd` it is referred to as an typedefed enum (so it refers to it as `comp_type`).

I tried this with a newer cython version and a newer gcc and clang version, so I'm not 100% sure whether this is a problem with the compiler or cython. However if @strahlex has tried it with just a newer gcc compiler, I think the problem pops up because gcc now does not accept referring to an enum without mentioning whereas it would ignore or just warn about it earlier.
